### ISSUE TITLE
 accessibility-fixer-upper

### ISSUE THREAD

**Issue by Kathleen-Chamberland** [Kathleen-Chamberland/accessibility-fixer-upper#1]
@muxlowc

Markbot is stuck at 18% and 15% difference but is not giving me anything that needs to be fixed

**Comment by muxlowc** [comment]
@Kathleen-Chamberland 

Hm so I think you maybe added classes, when you just needed to clean up some code:

1) remove the " pad-1-0 pad-b-1-2 push-1-4" from the `<li>` surrounding your Shrubs with laurels, and remove all of the pad-t's from your images.
2) where you have `<span>`, these should be `<p>`
3) your prices section,have just: pad-t pad-b and remove "push"
4) under the prices section, change your` <span>s to <p>s`
5) for your table caption: remove pad-t

that should be enough to get your started. Basically change spans to p's and remove the padding to alot of places. Just keep checking your markbot screenshots :)

**Comment by Kathleen-Chamberland** [comment]
Okay Thanks!
